# 03. Feature Engineering

This notebook converts the findings from exploratory data analysis into reproducible dataset versions for model training and comparison.

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd

## Environment Setup

In [2]:
PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
print("Project root configured.")

PROCESSED_DIR = PROJECT_ROOT / "data/processed"
print("Processed directory configured.")

Project root configured.
Processed directory configured.

In [3]:
from src.churn_ml.data import load_competition_data
from src.churn_ml.dataset_registry.constants import (
    V1_ENGINEERED_FEATURES,
    V2_SUMMARY_FEATURES,
    V3_ENGINEERED_FEATURES,
    V4_SUMMARY_FEATURES,
)
from src.churn_ml.features import (
    DatasetBuildSpec,
    PreparedDataset,
    add_missingness_indicator_features,
    add_missingness_pattern_feature,
    add_missingness_summary_features,
    add_selected_missing_indicators,
    add_selected_zero_indicators,
    add_zero_value_summary_features,
    deduplicate_missingness_mask_features,
    deduplicate_zero_mask_features,
    load_dataset,
    save_dataset,
    select_supported_zero_features,
)

## Metadata Loading

In [4]:
metadata_dir = PROJECT_ROOT / "data/interim/eda_metadata"


def load_feature_metadata(filename: str) -> list[str]:
    with (metadata_dir / filename).open("r", encoding="utf-8") as file:
        return json.load(file)


numeric_features = load_feature_metadata("numeric_features.json")
categorical_features = load_feature_metadata("categorical_features.json")
constant_features = load_feature_metadata("constant_features.json")
all_missing_features = load_feature_metadata("all_missing_features.json")
very_high_missing_features = load_feature_metadata("very_high_missing_features.json")

print(f"Numeric features:              {len(numeric_features)}")
print(f"Categorical features:          {len(categorical_features)}")
print(f"Constant features:             {len(constant_features)}")
print(f"All-missing features:          {len(all_missing_features)}")
print(f"Very high-missing features:    {len(very_high_missing_features)}")

Numeric features:              192
Categorical features:          38
Constant features:             25
All-missing features:          18
Very high-missing features:    136

## Dataset Loading

In [5]:
data = load_competition_data(
    train_path=PROJECT_ROOT / "data/raw/final_proj_data.csv",
    test_path=PROJECT_ROOT / "data/raw/final_proj_test.csv",
    sample_submission_path=(PROJECT_ROOT / "data/raw/final_proj_sample_submission.csv"),
)

print(f"Train features: {data.X.shape}")
print(f"Target:         {data.y.shape}")
print(f"Test features:  {data.test.shape}")

Train features: (10000, 230)
Target:         (10000,)
Test features:  (2500, 230)

## Data & Metadata Validation

In [6]:
train_columns = set(data.X.columns)

metadata_sets = {
    "numeric_features": set(numeric_features),
    "categorical_features": set(categorical_features),
    "constant_features": set(constant_features),
    "all_missing_features": set(all_missing_features),
    "very_high_missing_features": set(very_high_missing_features),
}

for name, features in metadata_sets.items():
    missing = features - train_columns
    extra = (
        train_columns - features
        if name
        in {
            "numeric_features",
            "categorical_features",
        }
        else set()
    )

    print(f"\n{name}")

    if missing:
        print(f"  Missing in dataset: {len(missing)}")
    else:
        print("  ✓ All metadata features exist in dataset")

    if extra:
        print(f"  Unclassified features: {len(extra)}")

numeric_features
  ✓ All metadata features exist in dataset
  Unclassified features: 38

categorical_features
  ✓ All metadata features exist in dataset
  Unclassified features: 192

constant_features
  ✓ All metadata features exist in dataset

all_missing_features
  ✓ All metadata features exist in dataset

very_high_missing_features
  ✓ All metadata features exist in dataset

## Dataset Version v0: Raw Minimal

In [7]:
features_to_drop = sorted(set(constant_features) | set(all_missing_features))

X_train_v0 = data.X.drop(columns=features_to_drop).copy()
X_test_v0 = data.test.drop(columns=features_to_drop).copy()

dataset_v0 = PreparedDataset(
    version="v0_raw_minimal",
    X_train=X_train_v0,
    y_train=data.y.copy(),
    X_test=X_test_v0,
    metadata={
        "description": (
            "Raw feature set with constant and all-missing features removed."
        ),
        "source": "raw",
        "dropped_features": features_to_drop,
        "n_dropped_features": len(features_to_drop),
        "n_train_rows": len(X_train_v0),
        "n_test_rows": len(X_test_v0),
        "n_features": X_train_v0.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v0_raw_minimal",
        parent_dataset_id=None,
        hypothesis=(
            "Removing constant and entirely missing "
            "features simplifies the feature schema "
            "without removing usable information."
        ),
        transformations=(
            {
                "type": "drop_columns",
                "declared_steps": [
                    (
                        "Remove features that are constant "
                        "in the training dataset."
                    ),
                    (
                        "Remove features that are entirely "
                        "missing in the training dataset."
                    ),
                    (
                        "Apply the same fixed removal list "
                        "to competition test data."
                    ),
                ],
            },
        ),
        target_dependency="none",
    ),
)

print(f"Dataset version:   {dataset_v0.version}")
print(f"Train shape:       {dataset_v0.X_train.shape}")
print(f"Target shape:      {dataset_v0.y_train.shape}")
print(f"Test shape:        {dataset_v0.X_test.shape}")
print(f"Dropped features:  {dataset_v0.metadata['n_dropped_features']}")

Dataset version:   v0_raw_minimal
Train shape:       (10000, 205)
Target shape:      (10000,)
Test shape:        (2500, 205)
Dropped features:  25

In [8]:
saved_path = save_dataset(
    dataset=dataset_v0, processed_dir=PROCESSED_DIR, overwrite=True
)

print(f"Saved to: {saved_path}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v0_raw_minimal

## Dataset Version v1: Missingness Summary

This version retains all features from `v0_raw_minimal` and adds row-level summaries of missing values.

The hypothesis is that patterns of unavailable information may contain useful information about customer type, service usage, or data-collection processes.

In [9]:
X_train_v1 = add_missingness_summary_features(
    X_train_v0,
    very_high_missing_features=very_high_missing_features,
)

X_test_v1 = add_missingness_summary_features(
    X_test_v0,
    very_high_missing_features=very_high_missing_features,
)

added_features_v1 = [
    column
    for column in X_train_v1.columns
    if column not in X_train_v0.columns
]

if list(X_train_v1.columns) != list(X_test_v1.columns):
    raise ValueError(
        "Train and test columns differ after missingness "
        "feature generation."
    )

if X_train_v1[added_features_v1].isna().any().any():
    raise ValueError(
        "Generated train missingness features contain missing values."
    )

if X_test_v1[added_features_v1].isna().any().any():
    raise ValueError(
        "Generated test missingness features contain missing values."
    )

dataset_v1 = PreparedDataset(
    version="v1_missingness_summary",
    X_train=X_train_v1,
    y_train=data.y.copy(),
    X_test=X_test_v1,
    metadata={
        "description": (
            "v0_raw_minimal with row-level missing-value "
            "summary features."
        ),
        "source": "v0_raw_minimal",
        "base_version": "v0_raw_minimal",
        "added_features": added_features_v1,
        "n_added_features": len(added_features_v1),
        "n_train_rows": len(X_train_v1),
        "n_test_rows": len(X_test_v1),
        "n_features": X_train_v1.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v1_missingness_summary",
        parent_dataset_id="v0_raw_minimal",
        hypothesis=(
            "Row-level missingness summaries contain useful information "
            "about customer state and data-collection patterns."
        ),
        transformations=(
            {
                "type": "additive_missingness_summary",
                "added_features": list(V1_ENGINEERED_FEATURES),
                "declared_steps": [
                    (
                        "Retain all features from v0_raw_minimal "
                        "without changing their values."
                    ),
                    "Add total missing-value count and rate.",
                    "Add numeric missing-value count and rate.",
                    "Add categorical missing-value count and rate.",
                    (
                        "Add missing-value count and rate across "
                        "very-high-missing features."
                    ),
                    (
                        "Calculate all summary features independently "
                        "for each row."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V1_ENGINEERED_FEATURES,
    ),
)

print(f"Dataset version:   {dataset_v1.version}")
print(f"Train shape:       {dataset_v1.X_train.shape}")
print(f"Test shape:        {dataset_v1.X_test.shape}")
print(f"Added features:    {len(added_features_v1)}")
print(*added_features_v1, sep="\n")

Dataset version:   v1_missingness_summary
Train shape:       (10000, 213)
Test shape:        (2500, 213)
Added features:    8
missing_count_total
missing_rate_total
missing_count_numeric
missing_rate_numeric
missing_count_categorical
missing_rate_categorical
missing_count_very_high
missing_rate_very_high

In [10]:
display(
    X_train_v1[added_features_v1]
    .describe()
    .T
)

,count,mean,std,min,25%,50%,75%,max
missing_count_total,10000.0,135.467700,4.947242,128.000000,132.000000,135.000000,137.000000,157.000000
missing_rate_total,10000.0,0.660818,0.024133,0.624390,0.643902,0.658537,0.668293,0.765854
missing_count_numeric,10000.0,131.530800,3.168889,128.000000,130.000000,131.000000,132.000000,148.000000
missing_rate_numeric,10000.0,0.769186,0.018532,0.748538,0.760234,0.766082,0.771930,0.865497
missing_count_categorical,10000.0,3.936900,2.850076,0.000000,2.000000,4.000000,6.000000,12.000000
missing_rate_categorical,10000.0,0.115791,0.083826,0.000000,0.058824,0.117647,0.176471,0.352941
missing_count_very_high,10000.0,126.343200,8.201155,94.000000,129.000000,129.000000,129.000000,129.000000
missing_rate_very_high,10000.0,0.979405,0.063575,0.728682,1.000000,1.000000,1.000000,1.000000

In [11]:
saved_path_v1 = save_dataset(
    dataset=dataset_v1,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v1}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v1_missingness_summary

## Dataset Version v2: Missingness Indicators

This version is built directly from `v0_raw_minimal`.

It adds:

- four row-level missing-value counts
- one binary missing-value indicator for every original feature that contains at least one missing value in the training dataset

The feature list is determined using training data only and is then applied unchanged to the test dataset.

In [12]:
missing_indicator_features_v2 = [
    column
    for column in X_train_v0.columns
    if X_train_v0[column].isna().any()
]

print(
    "Features with missing values in train: "
    f"{len(missing_indicator_features_v2)}"
)

print(
    "Expected new features: "
    f"{4 + len(missing_indicator_features_v2)}"
)

Features with missing values in train: 184
Expected new features: 188

In [13]:
X_train_v2 = add_missingness_indicator_features(
    X_train_v0,
    indicator_features=missing_indicator_features_v2,
    very_high_missing_features=very_high_missing_features,
)

X_test_v2 = add_missingness_indicator_features(
    X_test_v0,
    indicator_features=missing_indicator_features_v2,
    very_high_missing_features=very_high_missing_features,
)

added_features_v2 = [
    column
    for column in X_train_v2.columns
    if column not in X_train_v0.columns
]

indicator_columns_v2 = [
    f"{column}_is_missing"
    for column in missing_indicator_features_v2
]

summary_count_columns_v2 = [
    "missing_count_total",
    "missing_count_numeric",
    "missing_count_categorical",
    "missing_count_very_high",
]

c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result[indicator_column] = dataframe[column].isna().astype("int8")
c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\src\churn_ml\features.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [14]:
if list(X_train_v2.columns) != list(X_test_v2.columns):
    raise ValueError(
        "Train and test columns differ after v2 feature generation."
    )

if X_train_v2.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_train_v2[added_features_v2].isna().any().any():
    raise ValueError(
        "Generated train features contain missing values."
    )

if X_test_v2[added_features_v2].isna().any().any():
    raise ValueError(
        "Generated test features contain missing values."
    )

train_indicator_values = set(
    X_train_v2[indicator_columns_v2]
    .to_numpy()
    .ravel()
)

test_indicator_values = set(
    X_test_v2[indicator_columns_v2]
    .to_numpy()
    .ravel()
)

if not train_indicator_values.issubset({0, 1}):
    raise ValueError(
        "Train missing indicators contain values other than 0 and 1."
    )

if not test_indicator_values.issubset({0, 1}):
    raise ValueError(
        "Test missing indicators contain values other than 0 and 1."
    )

pd.testing.assert_frame_equal(
    X_train_v2[X_train_v0.columns],
    X_train_v0,
)

pd.testing.assert_frame_equal(
    X_test_v2[X_test_v0.columns],
    X_test_v0,
)

print("v2 validation passed.")

v2 validation passed.

In [15]:
dataset_v2 = PreparedDataset(
    version="v2_missingness_indicators",
    X_train=X_train_v2,
    y_train=dataset_v0.y_train.copy(),
    X_test=X_test_v2,
    metadata={
        "description": (
            "v0_raw_minimal with row-level missing counts "
            "and per-feature missing indicators."
        ),
        "source": "v0_raw_minimal",
        "base_version": "v0_raw_minimal",
        "summary_count_features": summary_count_columns_v2,
        "indicator_source_features": (
            missing_indicator_features_v2
        ),
        "indicator_features": indicator_columns_v2,
        "added_features": added_features_v2,
        "n_summary_count_features": (
            len(summary_count_columns_v2)
        ),
        "n_indicator_features": (
            len(indicator_columns_v2)
        ),
        "n_added_features": len(added_features_v2),
        "n_train_rows": len(X_train_v2),
        "n_test_rows": len(X_test_v2),
        "n_features": X_train_v2.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v2_missingness_indicators",
        parent_dataset_id="v0_raw_minimal",
        hypothesis=(
            "Feature-specific missingness patterns contain "
            "predictive information that is not fully represented "
            "by the original feature values."
        ),
        transformations=(
            {
                "type": "additive_broad_missingness_indicators",
                "summary_features": list(V2_SUMMARY_FEATURES),
                "indicator_suffix": "_is_missing",
                "declared_steps": [
                    (
                        "Retain all features from v0_raw_minimal "
                        "without changing their values."
                    ),
                    (
                        "Add row-level missing-value counts for total, "
                        "numeric, categorical, and very-high-missing "
                        "feature groups."
                    ),
                    (
                        "Select source features containing at least one "
                        "missing value in the training dataset."
                    ),
                    (
                        "Add one binary missing-value indicator for every "
                        "selected source feature."
                    ),
                    (
                        "Apply the fixed training-derived indicator source "
                        "list unchanged to competition test data."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V2_SUMMARY_FEATURES,
        use_missing_suffix=True,
    ),
)

print(f"Dataset version:    {dataset_v2.version}")
print(f"Train shape:        {dataset_v2.X_train.shape}")
print(f"Test shape:         {dataset_v2.X_test.shape}")
print(
    "Summary features:  "
    f"{len(summary_count_columns_v2)}"
)
print(
    "Indicator features:"
    f" {len(indicator_columns_v2)}"
)
print(f"Total added:        {len(added_features_v2)}")

Dataset version:    v2_missingness_indicators
Train shape:        (10000, 393)
Test shape:         (2500, 393)
Summary features:  4
Indicator features: 184
Total added:        188

In [16]:
display(
    X_train_v2[
        summary_count_columns_v2
    ]
    .describe()
    .T
)

display(
    pd.DataFrame(
        {
            "indicator": indicator_columns_v2,
            "train_missing_rate": [
                X_train_v2[column].mean()
                for column in indicator_columns_v2
            ],
            "test_missing_rate": [
                X_test_v2[column].mean()
                for column in indicator_columns_v2
            ],
        }
    )
    .sort_values(
        "train_missing_rate",
        ascending=False,
    )
    .head(30)
)

,count,mean,std,min,25%,50%,75%,max
missing_count_total,10000.0,135.4677,4.947242,128.0,132.0,135.0,137.0,157.0
missing_count_numeric,10000.0,131.5308,3.168889,128.0,130.0,131.0,132.0,148.0
missing_count_categorical,10000.0,3.9369,2.850076,0.0,2.0,4.0,6.0,12.0
missing_count_very_high,10000.0,126.3432,8.201155,94.0,129.0,129.0,129.0,129.0

             indicator  train_missing_rate  test_missing_rate
167  Var190_is_missing              0.9957             0.9956
77    Var92_is_missing              0.9957             0.9948
51    Var64_is_missing              0.9954             0.9940
36    Var45_is_missing              0.9922             0.9908
87   Var102_is_missing              0.9918             0.9920
83    Var98_is_missing              0.9896             0.9864
9     Var12_is_missing              0.9896             0.9864
49    Var62_is_missing              0.9896             0.9864
74    Var89_is_missing              0.9869             0.9836
137  Var156_is_missing              0.9869             0.9848
156  Var178_is_missing              0.9869             0.9836
119  Var136_is_missing              0.9869             0.9848
44    Var56_is_missing              0.9869             0.9836
50    Var63_is_missing              0.9869             0.9848
53    Var66_is_missing              0.9869             0.9848
42    Var53_is_missing              0.9867             0.9848
24    Var29_is_missing              0.9867             0.9848
33    Var41_is_missing              0.9867             0.9848
6      Var9_is_missing              0.9867             0.9848
38    Var47_is_missing              0.9867             0.9848
25    Var30_is_missing              0.9867             0.9848
40    Var50_is_missing              0.9867             0.9848
45    Var58_is_missing              0.9867             0.9848
0      Var1_is_missing              0.9867             0.9848
71    Var86_is_missing              0.9867             0.9848
85   Var100_is_missing              0.9867             0.9848
63    Var77_is_missing              0.9867             0.9848
93   Var108_is_missing              0.9867             0.9848
114  Var131_is_missing              0.9867             0.9848
112  Var129_is_missing              0.9867             0.9848

In [17]:
saved_path_v2 = save_dataset(
    dataset=dataset_v2,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v2}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v2_missingness_indicators

## Dataset Version v3: Targeted Missingness

This version is built on top of `v1_missingness_summary`.

It retains the eight row-level missingness summary features and adds binary missing-value indicators only for the source features that received meaningful importance in the broad `v2_missingness_indicators` experiment.

Selected source features:

- `Var217`
- `Var126`
- `Var218`
- `Var192`

This targeted approach tests whether the useful signal from individual missingness patterns can be preserved without adding the full set of noisy indicators.

In [18]:
targeted_indicator_features_v3 = [
    "Var217",
    "Var126",
    "Var218",
    "Var192",
]

missing_targeted_features = [
    column
    for column in targeted_indicator_features_v3
    if column not in X_train_v1.columns
]

if missing_targeted_features:
    raise KeyError(
        "Targeted source features are absent from v1: "
        f"{missing_targeted_features}"
    )

print(
    "Targeted missingness source features: "
    f"{len(targeted_indicator_features_v3)}"
)

print(*targeted_indicator_features_v3, sep="\n")

Targeted missingness source features: 4
Var217
Var126
Var218
Var192

In [19]:
X_train_v3 = add_selected_missing_indicators(
    X_train_v1,
    indicator_features=targeted_indicator_features_v3,
)

X_test_v3 = add_selected_missing_indicators(
    X_test_v1,
    indicator_features=targeted_indicator_features_v3,
)

indicator_columns_v3 = [
    f"{column}_is_missing"
    for column in targeted_indicator_features_v3
]

added_features_v3 = [
    column
    for column in X_train_v3.columns
    if column not in X_train_v1.columns
]

print(f"Added features: {added_features_v3}")

Added features: ['Var217_is_missing', 'Var126_is_missing', 'Var218_is_missing', 'Var192_is_missing']

In [20]:
if list(X_train_v3.columns) != list(X_test_v3.columns):
    raise ValueError(
        "Train and test columns differ after v3 feature generation."
    )

if X_train_v3.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_test_v3.columns.duplicated().any():
    raise ValueError(
        "Generated test dataset contains duplicate columns."
    )

if added_features_v3 != indicator_columns_v3:
    raise ValueError(
        "Unexpected set or order of generated v3 features."
    )

if X_train_v3[indicator_columns_v3].isna().any().any():
    raise ValueError(
        "Train targeted indicators contain missing values."
    )

if X_test_v3[indicator_columns_v3].isna().any().any():
    raise ValueError(
        "Test targeted indicators contain missing values."
    )

train_indicator_values = set(
    X_train_v3[indicator_columns_v3]
    .to_numpy()
    .ravel()
)

test_indicator_values = set(
    X_test_v3[indicator_columns_v3]
    .to_numpy()
    .ravel()
)

if not train_indicator_values.issubset({0, 1}):
    raise ValueError(
        "Train indicators contain values other than 0 and 1."
    )

if not test_indicator_values.issubset({0, 1}):
    raise ValueError(
        "Test indicators contain values other than 0 and 1."
    )

pd.testing.assert_frame_equal(
    X_train_v3[X_train_v1.columns],
    X_train_v1,
)

pd.testing.assert_frame_equal(
    X_test_v3[X_test_v1.columns],
    X_test_v1,
)

print("v3 validation passed.")

v3 validation passed.

In [21]:
dataset_v3 = PreparedDataset(
    version="v3_targeted_missingness",
    X_train=X_train_v3,
    y_train=dataset_v1.y_train.copy(),
    X_test=X_test_v3,
    metadata={
        "description": (
            "v1_missingness_summary with targeted per-feature "
            "missing indicators selected from the broad v2 experiment."
        ),
        "source": "v1_missingness_summary",
        "base_version": "v1_missingness_summary",
        "selection_source_experiment": (
            "xgboost_v2_missingness_indicators_cv5"
        ),
        "indicator_source_features": (
            targeted_indicator_features_v3
        ),
        "indicator_features": indicator_columns_v3,
        "added_features": added_features_v3,
        "n_added_features": len(added_features_v3),
        "n_train_rows": len(X_train_v3),
        "n_test_rows": len(X_test_v3),
        "n_features": X_train_v3.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v3_targeted_missingness",
        parent_dataset_id="v1_missingness_summary",
        hypothesis=(
            "A compact subset of feature-specific missingness "
            "indicators can preserve the useful signal found in "
            "the broad missingness-indicator experiment without "
            "adding the full noisy indicator set."
        ),
        transformations=(
            {
                "type": "additive_targeted_missingness_indicators",
                "indicator_source_features": [
                    "Var217",
                    "Var126",
                    "Var218",
                    "Var192",
                ],
                "added_features": list(V3_ENGINEERED_FEATURES),
                "selection_source_experiment": (
                    "xgboost_v2_missingness_indicators_cv5"
                ),
                "declared_steps": [
                    (
                        "Retain all original and generated features from "
                        "v1_missingness_summary without changing their values."
                    ),
                    (
                        "Use the fixed source-feature list Var217, Var126, "
                        "Var218, and Var192, selected from feature importance "
                        "in the xgboost_v2_missingness_indicators_cv5 experiment."
                    ),
                    (
                        "Add one binary missing-value indicator for each "
                        "selected source feature."
                    ),
                    (
                        "Apply the same fixed indicator list unchanged to "
                        "competition test data."
                    ),
                ],
            },
        ),
        target_dependency="exploratory",
        summary_features=V1_ENGINEERED_FEATURES,
        binary_indicator_features=V3_ENGINEERED_FEATURES,
    ),
)

print(f"Dataset version: {dataset_v3.version}")
print(f"Train shape:     {dataset_v3.X_train.shape}")
print(f"Target shape:    {dataset_v3.y_train.shape}")
print(f"Test shape:      {dataset_v3.X_test.shape}")
print(f"Added features:  {len(added_features_v3)}")

Dataset version: v3_targeted_missingness
Train shape:     (10000, 217)
Target shape:    (10000,)
Test shape:      (2500, 217)
Added features:  4

In [22]:
indicator_summary_v3 = pd.DataFrame(
    {
        "indicator": indicator_columns_v3,
        "train_rate": [
            X_train_v3[column].mean()
            for column in indicator_columns_v3
        ],
        "test_rate": [
            X_test_v3[column].mean()
            for column in indicator_columns_v3
        ],
    }
)

indicator_summary_v3["absolute_difference"] = (
    indicator_summary_v3["train_rate"]
    - indicator_summary_v3["test_rate"]
).abs()

display(
    indicator_summary_v3.sort_values(
        "absolute_difference",
        ascending=False,
    )
)

           indicator  train_rate  test_rate  absolute_difference
1  Var126_is_missing      0.2780     0.2848               0.0068
0  Var217_is_missing      0.0128     0.0156               0.0028
2  Var218_is_missing      0.0128     0.0156               0.0028
3  Var192_is_missing      0.0079     0.0084               0.0005

In [23]:
saved_path_v3 = save_dataset(
    dataset=dataset_v3,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v3}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v3_targeted_missingness

## Dataset Version v4: Zero-Value Summary

This version is built directly from `v0_raw_minimal`.

It adds target-independent row-level summaries of zero values across:

- all retained numerical features;
- numerical features with sufficiently supported zero and non-zero observations.

Supported zero-value features are selected using the training dataset only, without using the target. The resulting fixed feature list is then applied unchanged to the competition test dataset.

The hypothesis is that zero values may represent a meaningful customer state rather than an ordinary numerical value, and that aggregated zero-value patterns may provide additional predictive information.

In [24]:
numeric_source_features_v4 = [
    column
    for column in numeric_features
    if column in X_train_v0.columns
]

zero_support_thresholds_v4 = {
    "min_present": 1_000,
    "min_zero": 100,
    "min_nonzero": 100,
}

supported_zero_features_before_dedup_v4 = (
    select_supported_zero_features(
        X_train_v0,
        candidate_features=numeric_source_features_v4,
        **zero_support_thresholds_v4,
    )
)

(
    supported_zero_features_v4,
    zero_structure_groups_v4,
) = deduplicate_zero_mask_features(
    X_train_v0,
    features=supported_zero_features_before_dedup_v4,
)

duplicate_zero_structure_groups_v4 = [
    group
    for group in zero_structure_groups_v4
    if len(group) > 1
]

print(
    "Numerical source features: "
    f"{len(numeric_source_features_v4)}"
)

print(
    "Supported before deduplication: "
    f"{len(supported_zero_features_before_dedup_v4)}"
)

print(
    "Supported after deduplication: "
    f"{len(supported_zero_features_v4)}"
)

print("\nDuplicate zero/observation-mask groups:")

if duplicate_zero_structure_groups_v4:
    for group in duplicate_zero_structure_groups_v4:
        print(group)
else:
    print("None")

print("\nFinal supported source features:")
print(*supported_zero_features_v4, sep="\n")

Numerical source features: 171
Supported before deduplication: 33
Supported after deduplication: 25

Duplicate zero/observation-mask groups:
['Var112', 'Var76']
['Var123', 'Var38']
['Var133', 'Var160']
['Var134', 'Var25']
['Var140', 'Var7']
['Var149', 'Var24']
['Var153', 'Var22']
['Var163', 'Var85']

Final supported source features:
Var109
Var112
Var113
Var119
Var123
Var125
Var13
Var132
Var133
Var134
Var140
Var144
Var149
Var153
Var163
Var181
Var21
Var35
Var44
Var6
Var74
Var78
Var81
Var83
Var94

In [25]:
X_train_v4 = add_zero_value_summary_features(
    X_train_v0,
    numeric_features=numeric_source_features_v4,
    supported_zero_features=(
        supported_zero_features_v4
    ),
)

X_test_v4 = add_zero_value_summary_features(
    X_test_v0,
    numeric_features=numeric_source_features_v4,
    supported_zero_features=(
        supported_zero_features_v4
    ),
)

zero_summary_columns_v4 = [
    "zero_count_numeric",
    "zero_rate_observed_numeric",
    "zero_count_supported_numeric",
    "zero_rate_observed_supported_numeric",
]

added_features_v4 = [
    column
    for column in X_train_v4.columns
    if column not in X_train_v0.columns
]

print(f"Added features: {added_features_v4}")

Added features: ['zero_count_numeric', 'zero_rate_observed_numeric', 'zero_count_supported_numeric', 'zero_rate_observed_supported_numeric']

In [26]:
if not supported_zero_features_v4:
    raise ValueError(
        "No supported zero-value features were selected."
    )

if list(X_train_v4.columns) != list(X_test_v4.columns):
    raise ValueError(
        "Train and test columns differ after "
        "v4 feature generation."
    )

if X_train_v4.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_test_v4.columns.duplicated().any():
    raise ValueError(
        "Generated test dataset contains duplicate columns."
    )

if added_features_v4 != zero_summary_columns_v4:
    raise ValueError(
        "Unexpected set or order of generated v4 features."
    )

if (
    X_train_v4[zero_summary_columns_v4]
    .isna()
    .any()
    .any()
):
    raise ValueError(
        "Train zero-summary features contain missing values."
    )

if (
    X_test_v4[zero_summary_columns_v4]
    .isna()
    .any()
    .any()
):
    raise ValueError(
        "Test zero-summary features contain missing values."
    )

count_columns_v4 = [
    "zero_count_numeric",
    "zero_count_supported_numeric",
]

rate_columns_v4 = [
    "zero_rate_observed_numeric",
    "zero_rate_observed_supported_numeric",
]

if (
    X_train_v4[count_columns_v4]
    .lt(0)
    .any()
    .any()
):
    raise ValueError(
        "Train zero-count features contain negative values."
    )

if (
    X_test_v4[count_columns_v4]
    .lt(0)
    .any()
    .any()
):
    raise ValueError(
        "Test zero-count features contain negative values."
    )

if not (
    X_train_v4[rate_columns_v4]
    .ge(0)
    .all()
    .all()
    and X_train_v4[rate_columns_v4]
    .le(1)
    .all()
    .all()
):
    raise ValueError(
        "Train zero-rate features must be within [0, 1]."
    )

if not (
    X_test_v4[rate_columns_v4]
    .ge(0)
    .all()
    .all()
    and X_test_v4[rate_columns_v4]
    .le(1)
    .all()
    .all()
):
    raise ValueError(
        "Test zero-rate features must be within [0, 1]."
    )

if (
    X_train_v4["zero_count_numeric"].max()
    > len(numeric_source_features_v4)
):
    raise ValueError(
        "Train total zero count exceeds source-feature count."
    )

if (
    X_test_v4["zero_count_numeric"].max()
    > len(numeric_source_features_v4)
):
    raise ValueError(
        "Test total zero count exceeds source-feature count."
    )

if (
    X_train_v4["zero_count_supported_numeric"].max()
    > len(supported_zero_features_v4)
):
    raise ValueError(
        "Train supported zero count exceeds "
        "source-feature count."
    )

if (
    X_test_v4["zero_count_supported_numeric"].max()
    > len(supported_zero_features_v4)
):
    raise ValueError(
        "Test supported zero count exceeds "
        "source-feature count."
    )

pd.testing.assert_frame_equal(
    X_train_v4[X_train_v0.columns],
    X_train_v0,
)

pd.testing.assert_frame_equal(
    X_test_v4[X_test_v0.columns],
    X_test_v0,
)

print("v4 validation passed.")

v4 validation passed.

In [27]:
dataset_v4 = PreparedDataset(
    version="v4_zero_value_summary",
    X_train=X_train_v4,
    y_train=dataset_v0.y_train.copy(),
    X_test=X_test_v4,
    metadata={
        "description": (
            "v0_raw_minimal with target-independent "
            "row-level zero-value summary features."
        ),
        "source": "v0_raw_minimal",
        "base_version": "v0_raw_minimal",
        "numeric_source_features": (
            numeric_source_features_v4
        ),
        "supported_zero_source_features_before_deduplication": (
            supported_zero_features_before_dedup_v4
        ),
        "supported_zero_source_features": (
            supported_zero_features_v4
        ),
        "duplicate_zero_structure_groups": (
            duplicate_zero_structure_groups_v4
        ),
        "selection_thresholds": zero_support_thresholds_v4,
        "zero_summary_features": zero_summary_columns_v4,
        "added_features": added_features_v4,
        "n_numeric_source_features": (
            len(numeric_source_features_v4)
        ),
        "n_supported_zero_source_features_before_deduplication": (
            len(supported_zero_features_before_dedup_v4)
        ),
        "n_supported_zero_source_features": (
            len(supported_zero_features_v4)
        ),
        "n_duplicate_zero_structure_groups": (
            len(duplicate_zero_structure_groups_v4)
        ),
        "n_added_features": len(added_features_v4),
        "n_train_rows": len(X_train_v4),
        "n_test_rows": len(X_test_v4),
        "n_features": X_train_v4.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v4_zero_value_summary",
        parent_dataset_id="v0_raw_minimal",
        hypothesis=(
            "Row-level zero-value patterns across numerical "
            "features contain predictive information that is "
            "not fully represented by the original values."
        ),
        transformations=(
            {
                "type": "additive_zero_value_summary",
                "added_features": list(V4_SUMMARY_FEATURES),
                "selection_thresholds": {
                    "min_present": 1000,
                    "min_zero": 100,
                    "min_nonzero": 100,
                },
                "declared_steps": [
                    (
                        "Retain all features from v0_raw_minimal "
                        "without changing their values."
                    ),
                    (
                        "Define numerical source features as numerical "
                        "features retained in v0_raw_minimal."
                    ),
                    (
                        "Select supported numerical features using "
                        "training data only with min_present=1000, "
                        "min_zero=100, and min_nonzero=100."
                    ),
                    (
                        "Remove structurally duplicate supported features "
                        "whose zero-value and observed-value masks are both "
                        "identical in the training dataset."
                    ),
                    (
                        "Add the number of zero values across all "
                        "retained numerical features."
                    ),
                    (
                        "Add the zero-value rate among observed values "
                        "across all retained numerical features."
                    ),
                    (
                        "Add the number of zero values across supported "
                        "numerical features."
                    ),
                    (
                        "Add the zero-value rate among observed values "
                        "across supported numerical features."
                    ),
                    (
                        "Apply the fixed training-derived supported "
                        "feature list unchanged to competition test data."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V4_SUMMARY_FEATURES,
    ),
)

print(f"Dataset version: {dataset_v4.version}")
print(f"Train shape:     {dataset_v4.X_train.shape}")
print(f"Target shape:    {dataset_v4.y_train.shape}")
print(f"Test shape:      {dataset_v4.X_test.shape}")
print(f"Added features:  {len(added_features_v4)}")

Dataset version: v4_zero_value_summary
Train shape:     (10000, 209)
Target shape:    (10000,)
Test shape:      (2500, 209)
Added features:  4

In [28]:
display(
    X_train_v4[
        zero_summary_columns_v4
    ]
    .describe()
    .T
)

display(
    pd.DataFrame(
        {
            "feature": zero_summary_columns_v4,
            "train_mean": [
                X_train_v4[column].mean()
                for column in zero_summary_columns_v4
            ],
            "test_mean": [
                X_test_v4[column].mean()
                for column in zero_summary_columns_v4
            ],
        }
    ).assign(
        absolute_difference=lambda frame: (
            frame["train_mean"]
            - frame["test_mean"]
        ).abs()
    )
)

,count,mean,std,min,25%,50%,75%,max
zero_count_numeric,10000.0,12.029800,5.323922,1.000000,8.0,11.000000,14.000000,31.000000
zero_rate_observed_numeric,10000.0,0.312902,0.162742,0.030303,0.2,0.268293,0.358974,0.885714
zero_count_supported_numeric,10000.0,7.250900,3.915263,0.000000,5.0,7.000000,9.000000,22.000000
zero_rate_observed_supported_numeric,10000.0,0.301937,0.175297,0.000000,0.2,0.280000,0.375000,1.000000

,feature,train_mean,test_mean,absolute_difference
0,zero_count_numeric,12.029800,12.018400,0.011400
1,zero_rate_observed_numeric,0.312902,0.312995,0.000093
2,zero_count_supported_numeric,7.250900,7.177200,0.073700
3,zero_rate_observed_supported_numeric,0.301937,0.299803,0.002134

In [29]:
saved_path_v4 = save_dataset(
    dataset=dataset_v4,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v4}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v4_zero_value_summary

## Dataset Version v5: Joint Missingness Pattern

This version is built from `v1_missingness_summary`.

It adds one target-independent categorical feature representing the exact joint missingness pattern across structurally unique missingness masks.

The source features are determined using the training dataset only:

- retained original features containing missing values are identified;
- features with identical training missingness masks are grouped;
- the first feature in each group is retained as a representative;
- the resulting fixed ordered feature list is applied unchanged to competition test data.

The hypothesis is that the exact combination of jointly missing feature groups represents a customer or data-collection state that is not fully captured by row-level missingness counts.

No frequency encoding, rare-category grouping, or target encoding is materialized in this dataset.

In [30]:
missing_source_features_before_dedup_v5 = [
    column
    for column in X_train_v0.columns
    if X_train_v0[column].isna().any()
]

(
    missing_pattern_source_features_v5,
    missing_mask_groups_v5,
) = deduplicate_missingness_mask_features(
    X_train_v0,
    features=missing_source_features_before_dedup_v5,
)

duplicate_missing_mask_groups_v5 = [
    group
    for group in missing_mask_groups_v5
    if len(group) > 1
]

print(
    "Features containing missing values: "
    f"{len(missing_source_features_before_dedup_v5)}"
)

print(
    "Unique missingness-mask representatives: "
    f"{len(missing_pattern_source_features_v5)}"
)

print(
    "Duplicate missingness-mask groups: "
    f"{len(duplicate_missing_mask_groups_v5)}"
)

print("\nRepresentative source features:")
print(*missing_pattern_source_features_v5, sep="\n")

Features containing missing values: 184
Unique missingness-mask representatives: 34
Duplicate missingness-mask groups: 22

Representative source features:
Var1
Var3
Var4
Var5
Var6
Var7
Var12
Var22
Var24
Var33
Var45
Var51
Var56
Var59
Var63
Var64
Var71
Var72
Var88
Var92
Var101
Var102
Var126
Var189
Var190
Var192
Var194
Var197
Var200
Var205
Var217
Var219
Var225
Var229

In [31]:
X_train_v5 = add_missingness_pattern_feature(
    X_train_v1,
    source_features=missing_pattern_source_features_v5,
)

X_test_v5 = add_missingness_pattern_feature(
    X_test_v1,
    source_features=missing_pattern_source_features_v5,
)

missingness_pattern_feature_v5 = (
    "missingness_pattern_id"
)

added_features_v5 = [
    column
    for column in X_train_v5.columns
    if column not in X_train_v1.columns
]

train_pattern_count_v5 = (
    X_train_v5[
        missingness_pattern_feature_v5
    ].nunique()
)

test_pattern_count_v5 = (
    X_test_v5[
        missingness_pattern_feature_v5
    ].nunique()
)

test_pattern_seen_in_train_rate_v5 = (
    X_test_v5[
        missingness_pattern_feature_v5
    ]
    .isin(
        set(
            X_train_v5[
                missingness_pattern_feature_v5
            ]
        )
    )
    .mean()
)

print(f"Added features: {added_features_v5}")

print(
    "Unique train patterns: "
    f"{train_pattern_count_v5}"
)

print(
    "Unique test patterns: "
    f"{test_pattern_count_v5}"
)

print(
    "Test rows with a pattern seen in train: "
    f"{test_pattern_seen_in_train_rate_v5:.2%}"
)

Added features: ['missingness_pattern_id']
Unique train patterns: 693
Unique test patterns: 372
Test rows with a pattern seen in train: 97.60%

In [32]:
if list(X_train_v5.columns) != list(X_test_v5.columns):
    raise ValueError(
        "Train and test columns differ after "
        "v5 feature generation."
    )

if X_train_v5.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_test_v5.columns.duplicated().any():
    raise ValueError(
        "Generated test dataset contains duplicate columns."
    )

if added_features_v5 != [
    missingness_pattern_feature_v5
]:
    raise ValueError(
        "Unexpected set or order of generated v5 features."
    )

if (
    X_train_v5[
        missingness_pattern_feature_v5
    ]
    .isna()
    .any()
):
    raise ValueError(
        "Train missingness pattern contains missing values."
    )

if (
    X_test_v5[
        missingness_pattern_feature_v5
    ]
    .isna()
    .any()
):
    raise ValueError(
        "Test missingness pattern contains missing values."
    )

if (
    str(
        X_train_v5[
            missingness_pattern_feature_v5
        ].dtype
    )
    != "string"
):
    raise TypeError(
        "Train missingness pattern must use string dtype."
    )

if (
    str(
        X_test_v5[
            missingness_pattern_feature_v5
        ].dtype
    )
    != "string"
):
    raise TypeError(
        "Test missingness pattern must use string dtype."
    )

pd.testing.assert_frame_equal(
    X_train_v5[X_train_v1.columns],
    X_train_v1,
)

pd.testing.assert_frame_equal(
    X_test_v5[X_test_v1.columns],
    X_test_v1,
)

if not 0 <= test_pattern_seen_in_train_rate_v5 <= 1:
    raise ValueError(
        "Invalid test seen-pattern rate."
    )

print("v5 validation passed.")

v5 validation passed.

In [33]:
dataset_v5 = PreparedDataset(
    version="v5_joint_missingness_pattern",
    X_train=X_train_v5,
    y_train=dataset_v1.y_train.copy(),
    X_test=X_test_v5,
    metadata={
        "description": (
            "v1_missingness_summary with one categorical "
            "feature representing the exact joint "
            "missingness pattern."
        ),
        "source": "v1_missingness_summary",
        "base_version": "v1_missingness_summary",
        "pattern_source_base_version": (
            "v0_raw_minimal"
        ),
        "missing_source_features_before_deduplication": (
            missing_source_features_before_dedup_v5
        ),
        "missing_pattern_source_features": (
            missing_pattern_source_features_v5
        ),
        "duplicate_missing_mask_groups": (
            duplicate_missing_mask_groups_v5
        ),
        "pattern_feature": (
            missingness_pattern_feature_v5
        ),
        "pattern_representation": (
            "hex-encoded packed binary missingness mask"
        ),
        "added_features": added_features_v5,
        "n_missing_source_features_before_deduplication": (
            len(
                missing_source_features_before_dedup_v5
            )
        ),
        "n_missing_pattern_source_features": (
            len(missing_pattern_source_features_v5)
        ),
        "n_duplicate_missing_mask_groups": (
            len(duplicate_missing_mask_groups_v5)
        ),
        "n_train_patterns": train_pattern_count_v5,
        "n_test_patterns": test_pattern_count_v5,
        "test_pattern_seen_in_train_rate": (
            float(test_pattern_seen_in_train_rate_v5)
        ),
        "n_added_features": len(added_features_v5),
        "n_train_rows": len(X_train_v5),
        "n_test_rows": len(X_test_v5),
        "n_features": X_train_v5.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v5_joint_missingness_pattern",
        parent_dataset_id="v1_missingness_summary",
        hypothesis=(
            "The exact combination of jointly missing "
            "feature groups represents a customer or "
            "data-collection state that contains predictive "
            "information beyond row-level missingness counts."
        ),
        transformations=(
            {
                "type": "additive_joint_missingness_pattern",
                "pattern_feature": "missingness_pattern_id",
                "pattern_dtype": "string",
                "declared_steps": [
                    (
                        "Retain all original and generated features "
                        "from v1_missingness_summary without changing "
                        "their values."
                    ),
                    (
                        "Identify original v0_raw_minimal features "
                        "containing missing values in the training "
                        "dataset."
                    ),
                    (
                        "Group source features whose training "
                        "missingness masks are exactly identical."
                    ),
                    (
                        "Retain the first feature from each identical "
                        "missingness-mask group as a representative."
                    ),
                    (
                        "Pack the ordered representative missingness "
                        "mask into a deterministic hexadecimal string "
                        "categorical identifier."
                    ),
                    (
                        "Apply the fixed training-derived source "
                        "feature list and order unchanged to "
                        "competition test data."
                    ),
                    (
                        "Do not materialize frequency encoding, rare "
                        "category grouping, or target encoding."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V1_ENGINEERED_FEATURES,
    ),
)

print(f"Dataset version: {dataset_v5.version}")
print(f"Train shape:     {dataset_v5.X_train.shape}")
print(f"Target shape:    {dataset_v5.y_train.shape}")
print(f"Test shape:      {dataset_v5.X_test.shape}")
print(f"Added features:  {len(added_features_v5)}")

Dataset version: v5_joint_missingness_pattern
Train shape:     (10000, 214)
Target shape:    (10000,)
Test shape:      (2500, 214)
Added features:  1

In [34]:
pattern_diagnostics_v5 = pd.DataFrame(
    {
        "metric": [
            "source_features_before_deduplication",
            "source_features_after_deduplication",
            "duplicate_mask_groups",
            "unique_train_patterns",
            "unique_test_patterns",
            "test_seen_pattern_rate",
        ],
        "value": [
            len(
                missing_source_features_before_dedup_v5
            ),
            len(missing_pattern_source_features_v5),
            len(duplicate_missing_mask_groups_v5),
            train_pattern_count_v5,
            test_pattern_count_v5,
            test_pattern_seen_in_train_rate_v5,
        ],
    }
)

display(pattern_diagnostics_v5)

display(
    X_train_v5[
        missingness_pattern_feature_v5
    ]
    .value_counts()
    .rename_axis("missingness_pattern_id")
    .reset_index(name="train_count")
    .head(20)
)

                                 metric    value
0  source_features_before_deduplication  184.000
1   source_features_after_deduplication   34.000
2                 duplicate_mask_groups   22.000
3                 unique_train_patterns  693.000
4                  unique_test_patterns  372.000
5                test_seen_pattern_rate    0.976

   missingness_pattern_id  train_count
0              4ffebd1503          926
1              4ffe3d1503          625
2              4ffebd0500          389
3              4ffebd0100          351
4              4ffe3d0100          320
5              4ffebf1503          304
6              4ffe3d0500          294
7              4ffefd0100          219
8              4ffe3f1503          203
9              4ffebf0100          202
10             4ffefd0500          198
11             4ffebf9503          196
12             4ffebf0500          188
13             4ffe7d0100          187
14             4ffefd1503          173
15             4ffe3f0100          169
16             4ffe3f0500          166
17             4ffe7d0500          145
18             4ffeff0100          129
19             4ffe7f0100          123

In [35]:
saved_path_v5 = save_dataset(
    dataset=dataset_v5,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v5}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v5_joint_missingness_pattern

## Dataset Version v6: Compact Missingness Indicators

This version is built from `v1_missingness_summary`.

It adds one binary missingness indicator for each structurally unique column-level missingness mask.

The source features are determined from the original features retained in `v0_raw_minimal`:

- features containing missing values in the training dataset are identified;
- features with identical training missingness masks are grouped;
- the first feature in each group is retained as a representative;
- one binary indicator is added for every representative feature;
- the fixed representative list is applied unchanged to competition test data.

The hypothesis is that separate structurally unique missingness indicators preserve useful information about individual missingness states while removing the substantial redundancy present in the broad `v2_missingness_indicators` dataset.

The transformation does not use the target.

In [36]:
missing_source_features_before_dedup_v6 = [
    column
    for column in X_train_v0.columns
    if X_train_v0[column].isna().any()
]

(
    missing_indicator_source_features_v6,
    missing_mask_groups_v6,
) = deduplicate_missingness_mask_features(
    X_train_v0,
    features=missing_source_features_before_dedup_v6,
)

duplicate_missing_mask_groups_v6 = [
    group
    for group in missing_mask_groups_v6
    if len(group) > 1
]

indicator_columns_v6 = [
    f"{column}_is_missing"
    for column in missing_indicator_source_features_v6
]

print(
    "Features containing missing values: "
    f"{len(missing_source_features_before_dedup_v6)}"
)

print(
    "Unique missingness-mask representatives: "
    f"{len(missing_indicator_source_features_v6)}"
)

print(
    "Duplicate missingness-mask groups: "
    f"{len(duplicate_missing_mask_groups_v6)}"
)

print("\nRepresentative source features:")
print(*missing_indicator_source_features_v6, sep="\n")

Features containing missing values: 184
Unique missingness-mask representatives: 34
Duplicate missingness-mask groups: 22

Representative source features:
Var1
Var3
Var4
Var5
Var6
Var7
Var12
Var22
Var24
Var33
Var45
Var51
Var56
Var59
Var63
Var64
Var71
Var72
Var88
Var92
Var101
Var102
Var126
Var189
Var190
Var192
Var194
Var197
Var200
Var205
Var217
Var219
Var225
Var229

In [37]:
X_train_v6 = add_selected_missing_indicators(
    X_train_v1,
    indicator_features=missing_indicator_source_features_v6,
)

X_test_v6 = add_selected_missing_indicators(
    X_test_v1,
    indicator_features=missing_indicator_source_features_v6,
)

added_features_v6 = [
    column
    for column in X_train_v6.columns
    if column not in X_train_v1.columns
]

print(f"Added features: {len(added_features_v6)}")
print(*added_features_v6, sep="\n")

Added features: 34
Var1_is_missing
Var3_is_missing
Var4_is_missing
Var5_is_missing
Var6_is_missing
Var7_is_missing
Var12_is_missing
Var22_is_missing
Var24_is_missing
Var33_is_missing
Var45_is_missing
Var51_is_missing
Var56_is_missing
Var59_is_missing
Var63_is_missing
Var64_is_missing
Var71_is_missing
Var72_is_missing
Var88_is_missing
Var92_is_missing
Var101_is_missing
Var102_is_missing
Var126_is_missing
Var189_is_missing
Var190_is_missing
Var192_is_missing
Var194_is_missing
Var197_is_missing
Var200_is_missing
Var205_is_missing
Var217_is_missing
Var219_is_missing
Var225_is_missing
Var229_is_missing

In [38]:
if list(X_train_v6.columns) != list(X_test_v6.columns):
    raise ValueError(
        "Train and test columns differ after "
        "v6 feature generation."
    )

if X_train_v6.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_test_v6.columns.duplicated().any():
    raise ValueError(
        "Generated test dataset contains duplicate columns."
    )

if (
    len(missing_indicator_source_features_v6)
    != len(missing_mask_groups_v6)
):
    raise ValueError(
        "The number of representatives differs from "
        "the number of missingness-mask groups."
    )

if added_features_v6 != indicator_columns_v6:
    raise ValueError(
        "Unexpected set or order of generated v6 features."
    )

if X_train_v6[indicator_columns_v6].isna().any().any():
    raise ValueError(
        "Train missingness indicators contain missing values."
    )

if X_test_v6[indicator_columns_v6].isna().any().any():
    raise ValueError(
        "Test missingness indicators contain missing values."
    )

if not (
    X_train_v6[indicator_columns_v6]
    .isin([0, 1])
    .all()
    .all()
):
    raise ValueError(
        "Train missingness indicators must be binary."
    )

if not (
    X_test_v6[indicator_columns_v6]
    .isin([0, 1])
    .all()
    .all()
):
    raise ValueError(
        "Test missingness indicators must be binary."
    )

unexpected_train_dtypes_v6 = {
    column: str(X_train_v6[column].dtype)
    for column in indicator_columns_v6
    if str(X_train_v6[column].dtype) != "int8"
}

unexpected_test_dtypes_v6 = {
    column: str(X_test_v6[column].dtype)
    for column in indicator_columns_v6
    if str(X_test_v6[column].dtype) != "int8"
}

if unexpected_train_dtypes_v6:
    raise TypeError(
        "Unexpected train indicator dtypes: "
        f"{unexpected_train_dtypes_v6}"
    )

if unexpected_test_dtypes_v6:
    raise TypeError(
        "Unexpected test indicator dtypes: "
        f"{unexpected_test_dtypes_v6}"
    )

pd.testing.assert_frame_equal(
    X_train_v6[X_train_v1.columns],
    X_train_v1,
)

pd.testing.assert_frame_equal(
    X_test_v6[X_test_v1.columns],
    X_test_v1,
)

for source_feature, indicator_feature in zip(
    missing_indicator_source_features_v6,
    indicator_columns_v6,
    strict=True,
):
    expected_train_indicator = (
        X_train_v1[source_feature]
        .isna()
        .astype("int8")
        .rename(indicator_feature)
    )

    expected_test_indicator = (
        X_test_v1[source_feature]
        .isna()
        .astype("int8")
        .rename(indicator_feature)
    )

    pd.testing.assert_series_equal(
        X_train_v6[indicator_feature],
        expected_train_indicator,
    )

    pd.testing.assert_series_equal(
        X_test_v6[indicator_feature],
        expected_test_indicator,
    )

print("v6 validation passed.")

v6 validation passed.

In [39]:
dataset_v6 = PreparedDataset(
    version="v6_compact_missingness_indicators",
    X_train=X_train_v6,
    y_train=dataset_v1.y_train.copy(),
    X_test=X_test_v6,
    metadata={
        "description": (
            "v1_missingness_summary with one binary "
            "indicator for each structurally unique "
            "training missingness mask."
        ),
        "source": "v1_missingness_summary",
        "base_version": "v1_missingness_summary",
        "indicator_source_base_version": (
            "v0_raw_minimal"
        ),
        "missing_source_features_before_deduplication": (
            missing_source_features_before_dedup_v6
        ),
        "indicator_source_features": (
            missing_indicator_source_features_v6
        ),
        "duplicate_missing_mask_groups": (
            duplicate_missing_mask_groups_v6
        ),
        "indicator_features": indicator_columns_v6,
        "added_features": added_features_v6,
        "selection_rule": (
            "Retain the first source feature from each "
            "unique training missingness-mask group."
        ),
        "n_missing_source_features_before_deduplication": (
            len(missing_source_features_before_dedup_v6)
        ),
        "n_indicator_source_features": (
            len(missing_indicator_source_features_v6)
        ),
        "n_duplicate_missing_mask_groups": (
            len(duplicate_missing_mask_groups_v6)
        ),
        "n_indicator_features": len(indicator_columns_v6),
        "n_added_features": len(added_features_v6),
        "n_train_rows": len(X_train_v6),
        "n_test_rows": len(X_test_v6),
        "n_features": X_train_v6.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v6_compact_missingness_indicators",
        parent_dataset_id="v1_missingness_summary",
        hypothesis=(
            "Separate structurally unique missingness "
            "indicators preserve useful information about "
            "individual missingness states while avoiding "
            "the redundant indicators present in the broad "
            "missingness-indicator dataset."
        ),
        transformations=(
            {
                "type": "additive_compact_missingness_indicators",
                "indicator_suffix": "_is_missing",
                "declared_steps": [
                    (
                        "Retain all original and generated features "
                        "from v1_missingness_summary without changing "
                        "their values."
                    ),
                    (
                        "Identify original v0_raw_minimal features "
                        "containing missing values in the training "
                        "dataset."
                    ),
                    (
                        "Group source features whose training "
                        "missingness masks are exactly identical."
                    ),
                    (
                        "Retain the first source feature from each "
                        "identical missingness-mask group as a "
                        "representative."
                    ),
                    (
                        "Add one binary missingness indicator for "
                        "each representative source feature."
                    ),
                    (
                        "Apply the fixed training-derived source "
                        "feature list and order unchanged to "
                        "competition test data."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V1_ENGINEERED_FEATURES,
        binary_indicator_features=tuple(indicator_columns_v6),
    ),
)

print(f"Dataset version: {dataset_v6.version}")
print(f"Train shape:     {dataset_v6.X_train.shape}")
print(f"Target shape:    {dataset_v6.y_train.shape}")
print(f"Test shape:      {dataset_v6.X_test.shape}")
print(f"Added features:  {len(added_features_v6)}")

Dataset version: v6_compact_missingness_indicators
Train shape:     (10000, 247)
Target shape:    (10000,)
Test shape:      (2500, 247)
Added features:  34

In [40]:
missing_indicator_diagnostics_v6 = (
    pd.DataFrame(
        {
            "source_feature": (
                missing_indicator_source_features_v6
            ),
            "indicator_feature": indicator_columns_v6,
            "train_missing_rate": [
                X_train_v6[column].mean()
                for column in indicator_columns_v6
            ],
            "test_missing_rate": [
                X_test_v6[column].mean()
                for column in indicator_columns_v6
            ],
        }
    )
    .assign(
        absolute_difference=lambda frame: (
            frame["train_missing_rate"]
            - frame["test_missing_rate"]
        ).abs()
    )
    .sort_values(
        "absolute_difference",
        ascending=False,
    )
    .reset_index(drop=True)
)

display(
    pd.DataFrame(
        {
            "metric": [
                "source_features_before_deduplication",
                "source_features_after_deduplication",
                "duplicate_mask_groups",
                "added_indicator_features",
                "final_feature_count",
            ],
            "value": [
                len(
                    missing_source_features_before_dedup_v6
                ),
                len(
                    missing_indicator_source_features_v6
                ),
                len(duplicate_missing_mask_groups_v6),
                len(indicator_columns_v6),
                X_train_v6.shape[1],
            ],
        }
    )
)

display(missing_indicator_diagnostics_v6)

                                 metric  value
0  source_features_before_deduplication    184
1   source_features_after_deduplication     34
2                 duplicate_mask_groups     22
3              added_indicator_features     34
4                   final_feature_count    247

,source_feature,indicator_feature,train_missing_rate,test_missing_rate,absolute_difference
0,Var72,Var72_is_missing,0.4386,0.4540,0.0154
1,Var229,Var229_is_missing,0.5561,0.5692,0.0131
2,Var24,Var24_is_missing,0.1360,0.1472,0.0112
3,Var189,Var189_is_missing,0.5794,0.5692,0.0102
4,Var7,Var7_is_missing,0.1005,0.1088,0.0083
5,Var22,Var22_is_missing,0.0920,0.0996,0.0076
6,Var126,Var126_is_missing,0.2780,0.2848,0.0068
7,Var6,Var6_is_missing,0.1020,0.1084,0.0064
8,Var3,Var3_is_missing,0.9734,0.9688,0.0046
9,Var88,Var88_is_missing,0.9830,0.9788,0.0042
10,Var59,Var59_is_missing,0.9833,0.9796,0.0037
11,Var56,Var56_is_missing,0.9869,0.9836,0.0033
12,Var12,Var12_is_missing,0.9896,0.9864,0.0032
13,Var217,Var217_is_missing,0.0128,0.0156,0.0028
14,Var101,Var101_is_missing,0.9855,0.9828,0.0027
15,Var225,Var225_is_missing,0.5109,0.5136,0.0027
16,Var194,Var194_is_missing,0.7467,0.7488,0.0021
17,Var63,Var63_is_missing,0.9869,0.9848,0.0021
18,Var1,Var1_is_missing,0.9867,0.9848,0.0019
19,Var200,Var200_is_missing,0.4957,0.4972,0.0015
20,Var64,Var64_is_missing,0.9954,0.9940,0.0014
21,Var45,Var45_is_missing,0.9922,0.9908,0.0014
22,Var71,Var71_is_missing,0.9829,0.9820,0.0009
23,Var92,Var92_is_missing,0.9957,0.9948,0.0009
24,Var219,Var219_is_missing,0.1013,0.1004,0.0009
25,Var4,Var4_is_missing,0.9720,0.9712,0.0008
26,Var197,Var197_is_missing,0.0028,0.0020,0.0008
27,Var33,Var33_is_missing,0.9865,0.9872,0.0007
28,Var51,Var51_is_missing,0.9234,0.9240,0.0006
29,Var192,Var192_is_missing,0.0079,0.0084,0.0005
30,Var5,Var5_is_missing,0.9759,0.9756,0.0003
31,Var205,Var205_is_missing,0.0386,0.0388,0.0002
32,Var102,Var102_is_missing,0.9918,0.9920,0.0002
33,Var190,Var190_is_missing,0.9957,0.9956,0.0001

In [41]:
saved_path_v6 = save_dataset(
    dataset=dataset_v6,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v6}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v6_compact_missingness_indicators

In [42]:
loaded_v6 = load_dataset(
    version="v6_compact_missingness_indicators",
    processed_dir=PROCESSED_DIR,
)

pd.testing.assert_frame_equal(
    loaded_v6.X_train,
    dataset_v6.X_train.reset_index(drop=True),
)

pd.testing.assert_series_equal(
    loaded_v6.y_train,
    dataset_v6.y_train.reset_index(drop=True),
)

pd.testing.assert_frame_equal(
    loaded_v6.X_test,
    dataset_v6.X_test.reset_index(drop=True),
)

parent_v1_for_v6 = load_dataset(
    version="v1_missingness_summary",
    processed_dir=PROCESSED_DIR,
)

manifest_v6 = loaded_v6.dataset_manifest
manifest_v1_for_v6 = parent_v1_for_v6.dataset_manifest

if manifest_v6 is None or manifest_v1_for_v6 is None:
    raise ValueError(
        "Registry dataset_manifest.json is required for v6 validation."
    )

if manifest_v6.target.hash != manifest_v1_for_v6.target.hash:
    raise ValueError(
        "v6 target hash differs from parent dataset target hash."
    )

print("v6 round-trip validation passed.")

{
    "dataset_id": manifest_v6.dataset_id,
    "parent_dataset_id": manifest_v6.parent_dataset_id,
    "train_row_count": manifest_v6.train_row_count,
    "test_row_count": manifest_v6.test_row_count,
    "n_features": manifest_v6.n_features,
    "target_dependency": manifest_v6.target_dependency,
    "alignment_status": manifest_v6.row_identity.alignment_status,
    "schema_hash": manifest_v6.schema_hash,
    "target_hash": manifest_v6.target.hash,
}

C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(

v6 round-trip validation passed.

C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\889454716.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(

{'dataset_id': 'v6_compact_missingness_indicators',
 'parent_dataset_id': 'v1_missingness_summary',
 'n_train_rows': 10000,
 'n_test_rows': 2500,
 'n_features': 247,
 'target_dependency': 'none',
 'row_alignment_check': 'passed',
 'schema_hash': '332623cb0622a5efe6817c45488c70f57e63cde3e9f59d7a468e60e89d060620',
 'target_hash': '0ee6d23e3a1fe5891948c26381c756431d71a707c0dd24574050ba2cf267339f'}

## Dataset Version v7: Compact Zero Indicators

This version is built from `v4_zero_value_summary`.

It retains the four row-level zero-value summary features from `v4` and adds one binary zero-value indicator for each supported structurally unique numerical source feature.

The source-feature list is reused directly from the `v4_zero_value_summary` metadata:

- numerical features were selected using the training dataset only;
- each selected feature had at least 1,000 observed values, 100 zero values, and 100 non-zero values;
- features with identical training zero-value and observation masks were deduplicated;
- the resulting fixed ordered list contains 25 source features;
- the same source list is applied unchanged to competition test data.

The hypothesis is that the identity of the numerical features containing zero values provides predictive information beyond aggregate zero counts and rates.

Missing values are not treated as zero. The transformation does not use the target.

In [43]:
zero_indicator_source_features_v7 = list(
    dataset_v4.metadata[
        "supported_zero_source_features"
    ]
)

zero_support_thresholds_v7 = dict(
    dataset_v4.metadata[
        "selection_thresholds"
    ]
)

duplicate_zero_structure_groups_v7 = list(
    dataset_v4.metadata[
        "duplicate_zero_structure_groups"
    ]
)

zero_indicator_columns_v7 = [
    f"{column}_is_zero"
    for column in zero_indicator_source_features_v7
]

print(
    "Zero-indicator source features: "
    f"{len(zero_indicator_source_features_v7)}"
)

print(
    "Reused support thresholds: "
    f"{zero_support_thresholds_v7}"
)

print(
    "Duplicate zero-structure groups removed in v4: "
    f"{len(duplicate_zero_structure_groups_v7)}"
)

print("\nZero-indicator source features:")
print(*zero_indicator_source_features_v7, sep="\n")

Zero-indicator source features: 25
Reused support thresholds: {'min_present': 1000, 'min_zero': 100, 'min_nonzero': 100}
Duplicate zero-structure groups removed in v4: 8

Zero-indicator source features:
Var109
Var112
Var113
Var119
Var123
Var125
Var13
Var132
Var133
Var134
Var140
Var144
Var149
Var153
Var163
Var181
Var21
Var35
Var44
Var6
Var74
Var78
Var81
Var83
Var94

In [44]:
X_train_v7 = add_selected_zero_indicators(
    X_train_v4,
    indicator_features=zero_indicator_source_features_v7,
)

X_test_v7 = add_selected_zero_indicators(
    X_test_v4,
    indicator_features=zero_indicator_source_features_v7,
)

added_features_v7 = [
    column
    for column in X_train_v7.columns
    if column not in X_train_v4.columns
]

print(f"Added features: {len(added_features_v7)}")
print(*added_features_v7, sep="\n")

Added features: 25
Var109_is_zero
Var112_is_zero
Var113_is_zero
Var119_is_zero
Var123_is_zero
Var125_is_zero
Var13_is_zero
Var132_is_zero
Var133_is_zero
Var134_is_zero
Var140_is_zero
Var144_is_zero
Var149_is_zero
Var153_is_zero
Var163_is_zero
Var181_is_zero
Var21_is_zero
Var35_is_zero
Var44_is_zero
Var6_is_zero
Var74_is_zero
Var78_is_zero
Var81_is_zero
Var83_is_zero
Var94_is_zero

In [45]:
if list(X_train_v7.columns) != list(X_test_v7.columns):
    raise ValueError(
        "Train and test columns differ after "
        "v7 feature generation."
    )

if X_train_v7.columns.duplicated().any():
    raise ValueError(
        "Generated train dataset contains duplicate columns."
    )

if X_test_v7.columns.duplicated().any():
    raise ValueError(
        "Generated test dataset contains duplicate columns."
    )

if added_features_v7 != zero_indicator_columns_v7:
    raise ValueError(
        "Unexpected set or order of generated v7 features."
    )

if len(added_features_v7) != len(
    zero_indicator_source_features_v7
):
    raise ValueError(
        "The number of generated indicators differs from "
        "the number of source features."
    )

if X_train_v7[zero_indicator_columns_v7].isna().any().any():
    raise ValueError(
        "Train zero indicators contain missing values."
    )

if X_test_v7[zero_indicator_columns_v7].isna().any().any():
    raise ValueError(
        "Test zero indicators contain missing values."
    )

if not (
    X_train_v7[zero_indicator_columns_v7]
    .isin([0, 1])
    .all()
    .all()
):
    raise ValueError(
        "Train zero indicators must be binary."
    )

if not (
    X_test_v7[zero_indicator_columns_v7]
    .isin([0, 1])
    .all()
    .all()
):
    raise ValueError(
        "Test zero indicators must be binary."
    )

unexpected_train_dtypes_v7 = {
    column: str(X_train_v7[column].dtype)
    for column in zero_indicator_columns_v7
    if str(X_train_v7[column].dtype) != "int8"
}

unexpected_test_dtypes_v7 = {
    column: str(X_test_v7[column].dtype)
    for column in zero_indicator_columns_v7
    if str(X_test_v7[column].dtype) != "int8"
}

if unexpected_train_dtypes_v7:
    raise TypeError(
        "Unexpected train indicator dtypes: "
        f"{unexpected_train_dtypes_v7}"
    )

if unexpected_test_dtypes_v7:
    raise TypeError(
        "Unexpected test indicator dtypes: "
        f"{unexpected_test_dtypes_v7}"
    )

pd.testing.assert_frame_equal(
    X_train_v7[X_train_v4.columns],
    X_train_v4,
)

pd.testing.assert_frame_equal(
    X_test_v7[X_test_v4.columns],
    X_test_v4,
)

for source_feature, indicator_feature in zip(
    zero_indicator_source_features_v7,
    zero_indicator_columns_v7,
    strict=True,
):
    expected_train_indicator = (
        X_train_v4[source_feature]
        .eq(0)
        .astype("int8")
        .rename(indicator_feature)
    )

    expected_test_indicator = (
        X_test_v4[source_feature]
        .eq(0)
        .astype("int8")
        .rename(indicator_feature)
    )

    pd.testing.assert_series_equal(
        X_train_v7[indicator_feature],
        expected_train_indicator,
    )

    pd.testing.assert_series_equal(
        X_test_v7[indicator_feature],
        expected_test_indicator,
    )

print("v7 validation passed.")

v7 validation passed.

In [46]:
dataset_v7 = PreparedDataset(
    version="v7_compact_zero_indicators",
    X_train=X_train_v7,
    y_train=dataset_v4.y_train.copy(),
    X_test=X_test_v7,
    metadata={
        "description": (
            "v4_zero_value_summary with one binary "
            "zero-value indicator for each supported "
            "structurally unique numerical source feature."
        ),
        "source": "v4_zero_value_summary",
        "base_version": "v4_zero_value_summary",
        "indicator_source_base_version": (
            "v0_raw_minimal"
        ),
        "zero_indicator_source_features": (
            zero_indicator_source_features_v7
        ),
        "zero_indicator_features": (
            zero_indicator_columns_v7
        ),
        "support_thresholds": (
            zero_support_thresholds_v7
        ),
        "duplicate_zero_structure_groups_removed": (
            duplicate_zero_structure_groups_v7
        ),
        "added_features": added_features_v7,
        "selection_rule": (
            "Reuse the fixed supported and structurally "
            "deduplicated numerical source-feature list "
            "stored in v4_zero_value_summary metadata."
        ),
        "missing_value_rule": (
            "Missing values are encoded as not zero."
        ),
        "n_zero_indicator_source_features": (
            len(zero_indicator_source_features_v7)
        ),
        "n_zero_indicator_features": (
            len(zero_indicator_columns_v7)
        ),
        "n_duplicate_zero_structure_groups_removed": (
            len(duplicate_zero_structure_groups_v7)
        ),
        "n_added_features": len(added_features_v7),
        "n_train_rows": len(X_train_v7),
        "n_test_rows": len(X_test_v7),
        "n_features": X_train_v7.shape[1],
    },
    build_spec=DatasetBuildSpec(
        dataset_id="v7_compact_zero_indicators",
        parent_dataset_id="v4_zero_value_summary",
        hypothesis=(
            "The identity of numerical features containing "
            "zero values provides predictive information "
            "beyond aggregate row-level zero counts and rates."
        ),
        transformations=(
            {
                "type": "additive_compact_zero_indicators",
                "indicator_suffix": "_is_zero",
                "missing_value_rule": "missing_is_not_zero",
                "declared_steps": [
                    (
                        "Retain all original and generated features "
                        "from v4_zero_value_summary without changing "
                        "their values."
                    ),
                    (
                        "Reuse the fixed numerical source-feature "
                        "list selected in v4_zero_value_summary."
                    ),
                    (
                        "The reused source list was selected using "
                        "training data only with min_present=1000, "
                        "min_zero=100, and min_nonzero=100."
                    ),
                    (
                        "The reused source list excludes features "
                        "with identical training zero-value and "
                        "observed-value masks."
                    ),
                    (
                        "Add one binary zero-value indicator for "
                        "each retained source feature."
                    ),
                    (
                        "Encode missing values as not zero."
                    ),
                    (
                        "Apply the fixed source-feature list and "
                        "order unchanged to competition test data."
                    ),
                ],
            },
        ),
        target_dependency="none",
        summary_features=V4_SUMMARY_FEATURES,
        binary_indicator_features=tuple(zero_indicator_columns_v7),
    ),
)

print(f"Dataset version: {dataset_v7.version}")
print(f"Train shape:     {dataset_v7.X_train.shape}")
print(f"Target shape:    {dataset_v7.y_train.shape}")
print(f"Test shape:      {dataset_v7.X_test.shape}")
print(f"Added features:  {len(added_features_v7)}")

Dataset version: v7_compact_zero_indicators
Train shape:     (10000, 234)
Target shape:    (10000,)
Test shape:      (2500, 234)
Added features:  25

In [47]:
zero_indicator_diagnostics_v7 = (
    pd.DataFrame(
        {
            "source_feature": (
                zero_indicator_source_features_v7
            ),
            "indicator_feature": (
                zero_indicator_columns_v7
            ),
            "train_zero_rate": [
                X_train_v7[column].mean()
                for column in zero_indicator_columns_v7
            ],
            "test_zero_rate": [
                X_test_v7[column].mean()
                for column in zero_indicator_columns_v7
            ],
        }
    )
    .assign(
        absolute_difference=lambda frame: (
            frame["train_zero_rate"]
            - frame["test_zero_rate"]
        ).abs()
    )
    .sort_values(
        "absolute_difference",
        ascending=False,
    )
    .reset_index(drop=True)
)

display(
    pd.DataFrame(
        {
            "metric": [
                "zero_indicator_source_features",
                "duplicate_structure_groups_removed",
                "added_zero_indicators",
                "final_feature_count",
            ],
            "value": [
                len(zero_indicator_source_features_v7),
                len(duplicate_zero_structure_groups_v7),
                len(zero_indicator_columns_v7),
                X_train_v7.shape[1],
            ],
        }
    )
)

display(zero_indicator_diagnostics_v7)

                               metric  value
0      zero_indicator_source_features     25
1  duplicate_structure_groups_removed      8
2               added_zero_indicators     25
3                 final_feature_count    234

,source_feature,indicator_feature,train_zero_rate,test_zero_rate,absolute_difference
0,Var149,Var149_is_zero,0.3343,0.3172,0.0171
1,Var78,Var78_is_zero,0.8363,0.8232,0.0131
2,Var74,Var74_is_zero,0.4110,0.3988,0.0122
3,Var83,Var83_is_zero,0.3110,0.3000,0.0110
4,Var44,Var44_is_zero,0.8952,0.8880,0.0072
5,Var13,Var13_is_zero,0.2462,0.2392,0.0070
6,Var123,Var123_is_zero,0.1881,0.1812,0.0069
7,Var181,Var181_is_zero,0.8496,0.8436,0.0060
8,Var140,Var140_is_zero,0.2631,0.2580,0.0051
9,Var119,Var119_is_zero,0.0218,0.0264,0.0046
10,Var81,Var81_is_zero,0.0119,0.0164,0.0045
11,Var109,Var109_is_zero,0.0560,0.0516,0.0044
12,Var144,Var144_is_zero,0.2928,0.2968,0.0040
13,Var113,Var113_is_zero,0.0192,0.0232,0.0040
14,Var21,Var21_is_zero,0.0364,0.0404,0.0040
15,Var112,Var112_is_zero,0.1447,0.1408,0.0039
16,Var134,Var134_is_zero,0.1350,0.1312,0.0038
17,Var153,Var153_is_zero,0.0440,0.0476,0.0036
18,Var163,Var163_is_zero,0.2698,0.2664,0.0034
19,Var125,Var125_is_zero,0.2039,0.2012,0.0027
20,Var94,Var94_is_zero,0.0102,0.0124,0.0022
21,Var35,Var35_is_zero,0.8303,0.8320,0.0017
22,Var6,Var6_is_zero,0.0190,0.0200,0.0010
23,Var132,Var132_is_zero,0.7448,0.7452,0.0004
24,Var133,Var133_is_zero,0.0763,0.0764,0.0001

In [48]:
saved_path_v7 = save_dataset(
    dataset=dataset_v7,
    processed_dir=PROCESSED_DIR,
    overwrite=True,
)

print(f"Saved to: {saved_path_v7}")

Saved to: c:\Users\pbori\Documents\Courses\Neoversity\ML Foundations\neoversity-ml-final\data\processed\v7_compact_zero_indicators

In [49]:
loaded_v7 = load_dataset(
    version="v7_compact_zero_indicators",
    processed_dir=PROCESSED_DIR,
)

pd.testing.assert_frame_equal(
    loaded_v7.X_train,
    dataset_v7.X_train.reset_index(drop=True),
)

pd.testing.assert_series_equal(
    loaded_v7.y_train,
    dataset_v7.y_train.reset_index(drop=True),
)

pd.testing.assert_frame_equal(
    loaded_v7.X_test,
    dataset_v7.X_test.reset_index(drop=True),
)

parent_v4_for_v7 = load_dataset(
    version="v4_zero_value_summary",
    processed_dir=PROCESSED_DIR,
)

manifest_v7 = loaded_v7.dataset_manifest
manifest_v4_for_v7 = parent_v4_for_v7.dataset_manifest

if manifest_v7 is None or manifest_v4_for_v7 is None:
    raise ValueError(
        "Registry dataset_manifest.json is required for v7 validation."
    )

if manifest_v7.target.hash != manifest_v4_for_v7.target.hash:
    raise ValueError(
        "v7 target hash differs from parent dataset target hash."
    )

print("v7 round-trip validation passed.")

{
    "dataset_id": manifest_v7.dataset_id,
    "parent_dataset_id": manifest_v7.parent_dataset_id,
    "train_row_count": manifest_v7.train_row_count,
    "test_row_count": manifest_v7.test_row_count,
    "n_features": manifest_v7.n_features,
    "target_dependency": manifest_v7.target_dependency,
    "alignment_status": manifest_v7.row_identity.alignment_status,
    "schema_hash": manifest_v7.schema_hash,
    "target_hash": manifest_v7.target.hash,
}

C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(

v7 round-trip validation passed.

C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:6: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(
C:\Users\pbori\AppData\Local\Temp\ipykernel_50396\3629818896.py:16: FutureWarning: Mismatched null-like values None and nan found. In a future version, pandas equality-testing functions (e.g. assert_frame_equal) will consider these not-matching and raise.
  pd.testing.assert_frame_equal(

{'dataset_id': 'v7_compact_zero_indicators',
 'parent_dataset_id': 'v4_zero_value_summary',
 'n_train_rows': 10000,
 'n_test_rows': 2500,
 'n_features': 234,
 'target_dependency': 'none',
 'row_alignment_check': 'passed',
 'schema_hash': '94c07e6e011b222d1534f4a32be53751d1a89556865afb05d5582be47eb6ba13',
 'target_hash': '0ee6d23e3a1fe5891948c26381c756431d71a707c0dd24574050ba2cf267339f'}